"""Pydantic Schemas for Multi-Agent, MCP, and Reliability Layer.

Defines validated schemas for:
  - PlannerPlan
  - ToolRequest
  - ToolResponse
  - AgentResponse
  - ReviewResult
  - WorkflowResult
"""

from __future__ import annotations
from datetime import datetime
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field, field_validator, model_validator


# ─── Risk Level & Score Validation ───────────────────────────────────────────

VALID_RISK_LEVELS = {"LOW", "MEDIUM", "HIGH"}


def validate_risk_level(level: str | None) -> str | None:
    if level is not None:
        normalized = level.strip().upper()
        if normalized not in VALID_RISK_LEVELS:
            raise ValueError(f"Invalid risk level '{level}'. Must be one of {sorted(VALID_RISK_LEVELS)}")
        return normalized
    return None


def validate_risk_score(score: float | None) -> float | None:
    if score is not None:
        if not (0.0 <= score <= 100.0):
            raise ValueError(f"Risk score {score} out of bounds. Must be within [0.0, 100.0].")
    return score


# ─── 1. Planner Plan Schema ───────────────────────────────────────────────────

class PlannerPlan(BaseModel):
    """Structured execution plan generated by PlannerAgent."""

    intent: str = Field(..., description="Interpreted user intent")
    agents_required: List[Literal["analytics", "risk", "social", "knowledge"]] = Field(
        ..., min_length=1, description="List of specialist agents to invoke"
    )
    tools_planned: List[str] = Field(
        default_factory=list, description="Approved tool identifiers planned for execution"
    )
    target_district: Optional[str] = Field(None, description="Extracted Maharashtra district, if any")
    target_road_type: Optional[str] = Field(None, description="Extracted road classification, if any")
    reasoning: str = Field(..., description="Planner reasoning rationale")
    estimated_steps: int = Field(default=1, ge=1, le=10)


# ─── 2. Tool Request Schema ───────────────────────────────────────────────────

class ToolRequest(BaseModel):
    """Structured request sent to MCP server."""

    tool_name: str = Field(..., min_length=1, description="Name of the MCP tool to invoke")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Input arguments for tool")
    timeout_seconds: float = Field(default=10.0, ge=0.5, le=60.0, description="Execution timeout")
    caller_agent: Optional[str] = Field(None, description="Agent initiating the tool request")


# ─── 3. Tool Response Schema ──────────────────────────────────────────────────

class ToolResponse(BaseModel):
    """Structured response returned by MCP server."""

    tool_name: str = Field(..., description="Name of the tool executed")
    status: Literal["success", "error", "fallback"] = Field(..., description="Outcome status")
    data: Dict[str, Any] = Field(default_factory=dict, description="Tool payload returned")
    error: Optional[str] = Field(None, description="Error message if execution failed")
    execution_time_ms: float = Field(default=0.0, ge=0.0, description="Execution latency in ms")
    retry_count: int = Field(default=0, ge=0, le=5, description="Number of retry attempts made")

    @model_validator(mode="after")
    def validate_risk_data_if_present(self) -> "ToolResponse":
        """Verify any risk scores/levels in data are strictly valid."""
        if "risk_score" in self.data and self.data["risk_score"] is not None:
            validate_risk_score(float(self.data["risk_score"]))
        if "risk_level" in self.data and self.data["risk_level"] is not None:
            validate_risk_level(str(self.data["risk_level"]))
        if "risk_category" in self.data and self.data["risk_category"] is not None:
            validate_risk_level(str(self.data["risk_category"]))
        return self


# ─── 4. Agent Response Schema ─────────────────────────────────────────────────

class AgentResponse(BaseModel):
    """Structured response produced by a specialist agent."""

    agent_name: str = Field(..., description="Agent name identifier")
    status: Literal["success", "error", "skipped"] = Field(default="success")
    summary: str = Field(..., description="Text summary synthesized by agent")
    data: Dict[str, Any] = Field(default_factory=dict, description="Structured factual data")
    tools_called: List[str] = Field(default_factory=list, description="List of MCP tools invoked")
    error: Optional[str] = Field(None, description="Error message if any")
    latency_ms: float = Field(default=0.0, ge=0.0)


# ─── 5. Review Result Schema ──────────────────────────────────────────────────

class ReviewResult(BaseModel):
    """Quality and factual review report generated by ReviewerAgent."""

    is_approved: bool = Field(..., description="Whether response meets all safety and accuracy criteria")
    hallucination_risk: Literal["LOW", "MEDIUM", "HIGH"] = Field(
        ..., description="Evaluated risk of unsupported claims"
    )
    evidence_grounded: bool = Field(..., description="Whether claims are backed by tool data")
    numeric_claims_verified: bool = Field(..., description="Whether numbers match tool payloads")
    risk_levels_valid: bool = Field(..., description="Whether risk scores & levels conform to standard")
    missing_data_disclosed: bool = Field(..., description="Whether missing records are transparently reported")
    non_causal_social_verified: bool = Field(
        ..., description="Confirms social sentiment is NOT presented as accident cause"
    )
    recommendations_supported: bool = Field(
        ..., description="Confirms recommendations do not exceed evidence"
    )
    warnings: List[str] = Field(default_factory=list, description="Review warnings, if any")
    feedback: str = Field(default="", description="Review feedback or corrective remarks")
    disclaimer: str = Field(
        default="⚠️ ANALYTICAL NOTICE: All risk scores and rankings are historical outputs (2019-2023).",
        description="Mandatory system analytical notice"
    )
    hallucination_guarantee_statement: str = Field(
        default="Note: Independent verification is required; automated reviewers cannot guarantee 100% absence of hallucinations.",
        description="Explicit limitation disclaimer"
    )


# ─── 6. Workflow Result Schema ────────────────────────────────────────────────

class WorkflowResult(BaseModel):
    """End-to-end multi-agent execution outcome."""

    run_id: str = Field(..., description="Unique run identifier (UUID)")
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    query: str = Field(..., description="User query submitted")
    sanitized_query: str = Field(..., description="Sanitized query after input guardrails")
    plan: PlannerPlan = Field(..., description="Planner execution plan")
    agent_responses: Dict[str, AgentResponse] = Field(default_factory=dict)
    tools_executed: List[ToolResponse] = Field(default_factory=list)
    review: ReviewResult = Field(..., description="Review outcome")
    final_response: str = Field(..., description="Final validated response text")
    latency_ms: float = Field(default=0.0, ge=0.0)
    status: Literal["success", "rejected", "error"] = Field(default="success")
    error_message: Optional[str] = Field(None)
